Update Gen-Gherkin Feature File Template and Plugin Tests
DevOps-MBSE/aac-gen-gherkin pull request #17
Opened 2024-09-30 15:01 UTC by bunchw

# Description

Update to the feature file template and plugin tests

# Linked Items:

Closes/Fixes/Resolves #8 #10 

### Added

- _Describe any new features._

### Changed

- _Describe any changes in existing functionality._

### Deprecated

- _Describe any deprecated features._

### Removed

- _Describe any removed features._

### Fixed

- _Describe any bug fixes._

### Security

- _Describe any security-related changes._

# Checklist:

- [ ] I updated project documentation to reflect my changes.
- [ ] My changes generate no new warnings.
- [ ] I updated new and existing unit tests to account for my changes.
- [ ] I linked the associated item(s) to be closed.
- [ ] I bumped the version.
- [ ] I added the labels corresponding to my changes.

2024-09-30 15:37 UTC, lizzcondrey requested changes
Here's findings from just visual checks. About to go and manually test things.

2024-09-30 15:37 UTC, lizzcondrey commented on python/tests/test_generate_gherkin_feature_files.py
>          # TODO:  assert the output message is correct
You still need to accommodate some of these TODOs. And be sure to remove the reminders once incorporated.

The success message should be evaluated for expected output.

2024-09-30 15:37 UTC, lizzcondrey commented on python/tests/test_generate_gherkin_feature_files.py
> +            self.assertTrue(len(output_message) > 0)
Not really understanding the point of this test?

2024-09-30 15:37 UTC, lizzcondrey commented on python/tests/test_generate_gherkin_feature_files.py
> +                self.assertIn("Feature:", temp_content)
I would expand and check for all the expected entry sections to the file, i.e. given, when, then steps. Feature file is useless if that isn't being populated.

2024-09-30 15:37 UTC, lizzcondrey commented on python/src/gen_gherkin/generate_gherkin_feature_files_impl.py
> +        behavior_list = []
Sure this is needed? See you add it here but don't see it referenced in your other changes.

2024-09-30 15:37 UTC, lizzcondrey commented on python/src/gen_gherkin/gen_gherkin_helpers.py
> +import re
```suggestion
from re import sub

from aac.context.definition import Definition
```

Remember to keep your imports organized, external first then internals. And remember to try to stick to using `from x import y` to keep from ballooning the install.

2024-09-30 15:37 UTC, lizzcondrey commented on python/src/gen_gherkin/generate_gherkin_feature_files_impl.py
> +
```suggestion
```

Looks like an extra blank line was added

2024-09-30 15:37 UTC, lizzcondrey commented on python/tests/calc/model/calculator.yaml
> +    - name: Perform simple math function (add or subtract)
```suggestion
    - name: Perform simple math functions
```

The provided scenarios do more than just add and subtract.

2024-09-30 15:37 UTC, lizzcondrey commented on python/tests/calc/model/calculator.yaml
> +      description: Add or subtract numbers
```suggestion
      description: Add, subtract, multiply, and divide two numbers.
```

2024-09-30 15:37 UTC, lizzcondrey commented on python/tests/test_generate_gherkin_feature_files.py
> +from tempfile import TemporaryDirectory
```suggestion
from tempfile import TemporaryDirectory
from typing import Tuple
```

remember to keep imports alphabetized to be easier to navigate when there is multiple.

2024-09-30 15:59 UTC, lizzcondrey commented
Looks like something is happening incorrectly for the sorting of when requirements are encountered within a scenario and not top level feature assignment.

If you run the `gen-gherkin-behaviors` command on the `calculator.yaml` file, `mathmessagehandler_api_feature_file` output has the requirement for `SQRT-2` put with the first scenario vs the second like it is assigned within the `mathmessagehandler.yaml` definition file.

2024-09-30 19:22 UTC, lizzcondrey commented
Remember to utilize the PR checklist, have some things missing for this PR.

2024-09-30 19:39 UTC, lizzcondrey requested changes
Remember to utilize the PR checklist, have some things missing for this PR. 

And remember to review the AC of the tasks. You've not got this connected up for being evaluated by behave like we've decided to try and accommodate going forward. 

Some helpful references.
https://semaphoreci.com/community/tutorials/getting-started-with-behavior-testing-in-python-with-behave
https://github.com/DevOps-MBSE/AaC/tree/main/python/features

2024-10-01 14:29 UTC, lizzcondrey requested changes

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +from behave import *
This should not be left as a wild card.

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +from os import listdir, path
```suggestion
from click.testing import CliRunner
from os import listdir, path
from shutil import rmtree
from tempfile import TemporaryDirectory
from typing import Tuple
```

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +def step_check(context, architecture_file):
Docstring

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +def step_impl(context, output_directory):
Docstring

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +def step_result(context):
Docstring

2024-10-01 14:29 UTC, lizzcondrey commented on python/tests/generate_gherkin_feature_files_output_gherkin_feature_files.feature
Don't believe this file should remain here since it's been moved to the proper directory to be picked up by behave. Thoughts on us including a header note about if wanting to leverage the behave testing moving it? Or think we should update generate to output this file to the appropriate spot? Does the `features` directory have to be at root, or could it be under tests and get picked up?

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
Wonder if we should expand `generate` to include a boilerplate steps file? Or could make an additional flag with `gen-plugin` of wanting to leverage behave testing to drive output of this file and other infrastructure for the behave testing? Thoughts?

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +    assert(0 == exit_code)
```suggestion
    assert (0 == exit_code)
```

Looks like a space after `assert` is preferred

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +    assert(0 != len(temp_dir_files))
```suggestion
    assert (0 != len(temp_dir_files))
```
Looks like a space after `assert` is preferred

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
> +    assert(path.isdir(context.output_directory) == False)
```suggestion
    assert (path.isdir(context.output_directory) == False)
```
Looks like a space after `assert` is preferred

2024-10-01 14:29 UTC, lizzcondrey commented on python/features/steps/steps.py
Also, looks like there is a chunk of formatting clean-up to be done within this file. Make sure you check the linter.

2024-10-01 14:38 UTC, bunchw commented on python/tests/generate_gherkin_feature_files_output_gherkin_feature_files.feature
You can put it under tests if you include a path in the behave command.  If you just call behave it will only search for the features directory at root.

2024-10-01 14:39 UTC, bunchw commented on python/features/steps/steps.py
We could include a steps file with empty given, when, and then methods.

2024-10-01 14:44 UTC, lizzcondrey commented on python/features/steps/steps.py
So, provide something like our stubbed unit test file as part of `gen-plugin` test output?

2024-10-01 14:47 UTC, lizzcondrey commented on python/tests/generate_gherkin_feature_files_output_gherkin_feature_files.feature
Okay, so that would come down to a "design" choice then. Can either add an additional output for the test handling to create the `features` directory. Or, can put it under tests and can update the command for finding it to include the path it's looking for of something like `tests/features`?

2024-10-01 17:35 UTC, lizzcondrey requested changes

2024-10-01 17:35 UTC, lizzcondrey commented on python/features/steps/steps.py
> +from os import listdir, path
```suggestion
from os import listdir, path
from shutil import rmtree
from typing import Tuple
```

2024-10-01 17:35 UTC, lizzcondrey commented on python/features/steps/steps.py
> +    Runs check on the given architecture_file.
```suggestion
    Runs check on the given architecture file.
```

2024-10-01 17:35 UTC, lizzcondrey commented on python/features/steps/steps.py
> +    Runs the aac-gen-gherkin command.
```suggestion
    Runs the aac-gen-gherkin-behaviors command.
```

2024-10-01 17:35 UTC, lizzcondrey commented on python/features/steps/steps.py
> +        output_directory (str): The directory that the gen-gherkin command will output to.
```suggestion
        output_directory (str): The directory that the gen-gherkin-behaviors command will output to.
```

2024-10-01 21:25 UTC, lizzcondrey approved these changes
Looks good, we just need to wrap up the remaining conversations or capture them to be followed up on in a different venue.

2024-10-02 14:16 UTC, bunchw commented on python/features/steps/steps.py
Yeah that would work.

2024-10-02 14:17 UTC, bunchw commented on python/tests/generate_gherkin_feature_files_output_gherkin_feature_files.feature
I feel like it would be simpler to create a features directory and put it there, like what we have in core aac.

2024-10-02 14:39 UTC, merged